### ISSUE TITLE
body 全体で letter-spacing が効いてるので間延びして見える

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-jungfrau#7]
letter-spacing: 0.2em;

が body で指定されているので全体的に間延びしてみると。と指摘あり。

**Comment by wtnbtkfm** [comment]
これは狙ってやっているところでもあります。
は私の感覚だと、間延びというか字間を多く取ることですっきり綺麗を与えられているかと。
Jungfrauは全体的にホワイトスペース多めなデザインになっているでちょっと字間や行間は広めにしたいなと思っています。

とはいえ、この辺りは見る人で受け取り方が変わると思うので難しいところですね、、、
私的にはこのままか、ちょっと狭めて
`letter-spacing: 0.1em;`
これくらいにするかかな？と思っていますがいかがでしょうか？

0にしてしまうと、かなり印象が変わって狭苦しい感じになると思います。

**Comment by yuji** [comment]
@wtnbtkfm 
英語が空きすぎるんだと思う。日本語はspacing効いてる方が読みやすくなるけど。
英語だけって出来ないよね・・・。
であれば0.1くらいが妥当かなあ

**Comment by wtnbtkfm** [comment]
@yuji 
MTの言語設定で英語の時は<html lang="en">、日本語の時は<html lang="ja">として、それぞれにスタイルを当てることはできるといえばできるんですが、そういう話ではないですよね？
英語と日本語が混在している状態で英語だけspacingを変えるのはちょっと厳しそうですね、、、

取り急ぎ0.1に修正してみました。
http://172.31.58.170/jungfrau/
これくらいが無難な気がしますね。

**Comment by yuji** [comment]
@wtnbtkfm そだね。これでいきましょうか

**Comment by wtnbtkfm** [comment]
修正完了。

**Comment by wtnbtkfm** [comment]
対応完了しているのでクローズします。
